apiVersion: hive.openshift.io/v1alpha1
kind: SelectorSyncSet
metadata:
  generation: 1
  name: osd-quota-exempt-openshift-monitoring
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: "true"
  resourceApplyMode: sync
  patches:
  - kind: Namespace
    apiVersion: v1
    name: openshift-monitoring
    applyMode: AlwaysApply
    # User of the template will substitute in the labels to apply in JSON notation.
    patch: |-
      { "metadata": {"labels": {"storage_pv_quota":"False"},{"service_lb_quota":"False"} } }
    patchType: merge
